### ISSUE TITLE
Preparation for v0.13.0

### ISSUE THREAD

**Issue by catostrophe** [trace4cats/trace4cats#662]
3 months have passed since 0.12.0. There have been not many changes in t4c libs since then, but a lot of dependencies have been bumped. I think it's time to close some issues and cut 0.13.0 just to show the users we keep t4c up-to-date 😃 

If anyone has ideas about what else can be improved before the new release, please open an issue.

Below is the list of issues that should be fixed before the release:

 - [x] trace4cats/trace4cats-dynamic-extras#52
 - [x] trace4cats/trace4cats-newrelic#55
 - [ ] trace4cats/trace4cats-sttp#82
 - [ ] trace4cats/trace4cats-sttp#90

Issues that may be fixed:
 - [ ] #630 blocked by typelevel/cats-effect#2416
 - [ ] trace4cats/trace4cats-http4s#47

Issues related to `trace4cats-components`:
 - [ ] trace4cats/trace4cats-components#10
 - [ ] trace4cats/trace4cats-components#37
 - [ ] trace4cats/trace4cats-components#38

Issues related to flaky tests (low-priority):
 - [ ] trace4cats/trace4cats-jaeger-integration-test#19
 - [ ] trace4cats/trace4cats-jaeger-integration-test#18
 - [ ] trace4cats/trace4cats-zipkin#22

Other issues (low-priority):
 - [ ] trace4cats/trace4cats-zio#50

**Comment by catostrophe** [comment]
v0.13.0 has been released. Some of the issues above haven't been resolved. If we fix them soon, we can cut v0.13.1 where needed.
